name: Synopsys Scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  AppSec_Pipeline:
    name: Synopsys Security Scans
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
#      - run: bundle install
      
      - name: Static Analysis with Polaris Action
        uses: devsecops-test/polaris-action@v1
        with:
          polarisServerUrl: ${{ secrets.POLARIS_SERVER_URL }}
          polarisAccessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polarisProjectName: HVP-railsgoat

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: polaris-scan-results.sarif.json

#      - name: Software Composition Analysis with Black Duck
#        uses: blackducksoftware/github-action@v2
#        with:
#          version: 7
#          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.project.description="Demo of RailsGoat Ruby project from GitHub Pipeline" --detect.project.name="HVP-railsgoat" --detect.project.version.phase=DEVELOPMENT --detect.bom.aggregate.name="railsgoat_bom" --detect.tools="SIGNATURE_SCAN,DETECTOR"'

      - name: Synopsys Detect Rescan
        run: >
          curl -s -L https://raw.github.com/matthewb66/detect_rescan/main/detect_rescan.sh > detect_rescan.sh; 
          bash detect_rescan.sh --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.project.description="Demo of RailsGoat Ruby project from GitHub Pipeline" --detect.project.name="HVP-railsgoat" --detect.project.version.name="development" --detect.project.version.phase=DEVELOPMENT --detect.tools="SIGNATURE_SCAN,DETECTOR" --quiet --testxml --report
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/policies.xml'
          check_name: 'Black Duck SCA Scan Results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
